Revert
Notice: Use of undefined constant _PS_CONFIG_DIR_ - assumed '_PS_CONFIG_DIR_' in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 30

Warning: include(_PS_CONFIG_DIR_/config.inc.php): failed to open stream: No such file or directory in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 30

Warning: include(): Failed opening '_PS_CONFIG_DIR_/config.inc.php' for inclusion (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 30

Notice: Use of undefined constant _PS_CONFIG_DIR_ - assumed '_PS_CONFIG_DIR_' in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 31

Warning: include(_PS_CONFIG_DIR_/../init.php): failed to open stream: No such file or directory in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 31

Warning: include(): Failed opening '_PS_CONFIG_DIR_/../init.php' for inclusion (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 31

Fatal error: Uncaught Error: Class 'Tools' not found in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php:34 Stack trace: #0 {main} thrown in C:\laragon\www\prestashop1.7.5\modules\gsitemap\gsitemap-cron.php on line 34